version: '3.7'
services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate user_app 0018_customuser_birthday_customuser_phone_number &&
             python3 manage.py migrate &&
             python3 manage.py setup &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/Cinema/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cinema
volumes:
  postgres_data: