version: '3.7'
services:
  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate user_app 0018_customuser_birthday_customuser_phone_number &&
             python3 manage.py migrate &&
             python3 manage.py setup &&
             python manage.py collectstatic &&
             gunicorn Cinema.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - media_volume:/home/Cinema/web/mediafiles
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cinema
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - media_volume:/home/Cinema/web/mediafiles
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
volumes:
  postgres_data:
  media_volume:

