from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('', views.statistic, name='statistic'),
    path('add_movie', views.add_movie, name='add_movie'),
    path('delete', views.delete_by_seo, name='delete_by_seo'),
    path('choose_users', views.choose_users, name='choose_users'),
    path('get_movies', views.get_movies, name='get_movies'),
    path('get_sessions', views.get_sessions, name='get_sessions'),
    path('add_template', views.add_template, name='add_template'),
    path('get_templates', views.get_templates, name='get_templates'),
    path('delete_template', views.delete_template, name='delete_template'),
    path('get_users_gender', views.get_users_gender, name='get_users_gender'),
    path('add_cinema', views.add_cinema, name='add_cinema'),
    path('add_page', views.add_page, name='add_page'),
    path('add_news', views.add_news, name='add_news'),
    path('add_disc', views.add_disc, name='add_discounts'),
    path('add_hall/<int:cinema_number>', views.add_hall, name='add_hall'),
    path('delete_hall/<int:hall_id>', views.delete_hall, name='delete_hall'),
    path('delete_pages/<int:page_id>', views.delete_page, name='delete_page'),
    path('delete_movie/<int:movie_id>', views.delete_movie, name='delete_movie'),
    path('delete_discounts/<int:discount_id>', views.delete_discounts, name='delete_discounts'),
    path('delete_news/<int:news_id>', views.delete_news, name='delete_news'),
    path('delete_news/<int:news_id>', views.delete_news, name='delete_news'),
    path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),
    path('change_banners', views.change_banners, name='change_banners'),
    path('change_contacts', views.change_contacts, name='change_contacts'),
    path('change_changeNewsAndDiskInBanner', views.changeNewsAndDiskInBanner, name='change_changeNewsAndDiskInBanner'),
    path('change_main', views.change_main, name='change_main'),
    path('movies', views.movies, name='movies'),
    path('users', views.users, name='users'),
    path('create_sessions', views.create_sessions, name='create_sessions'),
    path('send_email', views.send_email, name='send_email'),
    path('prepare_sending', views.prepare_sending, name='prepare_sending'),
    path('pages', views.pages, name='pages'),
    path('cinemas', views.cinemas, name='cinemas'),
    path('news', views.news, name='news'),
    path('discounts', views.discounts, name='discounts'),
    path('halls/<slug:url>', views.change_hall, name='change_hall'),
    path('movies/<slug:url>', views.change_movie, name='change_movie'),
    path('cinemas/<slug:url>', views.change_cinema, name='change_cinema'),
    path('pages/<slug:url>', views.change_page, name='change_page'),
    path('users/<slug:username>', views.change_user, name='change_user'),
    path('news/<slug:url>', views.change_news, name='change_news'),
    path('discounts/<slug:url>', views.change_discount, name='change_discount'),
]
