# Generated by Django 4.0.6 on 2022-09-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0017_alter_session_time'),
        ('user_app', '0008_alter_ticket_place'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('session', 'place')},
        ),
    ]
