# Generated by Django 4.0.6 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0017_alter_session_time'),
        ('user_app', '0009_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ticket',
            name='row',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('session', 'place', 'row')},
        ),
    ]
