# Generated by Django 4.0.6 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_ticket_unique_together_ticket_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='place',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='row',
            field=models.CharField(max_length=8),
        ),
    ]
