# Generated by Django 4.0.6 on 2022-09-12 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_ticket_place_alter_ticket_row'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
