# Generated by Django 4.1.1 on 2022-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_alter_customuser_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Different', 'Different')], max_length=32, null=True),
        ),
    ]
