# Generated by Django 4.0.6 on 2022-08-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0004_alter_seo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
