# Generated by Django 4.0.6 on 2022-08-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0007_alter_seo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanddiscinbanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
