# Generated by Django 4.0.6 on 2022-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0009_remove_newsanddiscinbanner_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscount',
            name='type',
            field=models.CharField(choices=[('News', 'News'), ('Discount', 'Discount')], default='News', max_length=16),
        ),
    ]
