# Generated by Django 4.0.6 on 2022-08-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0011_alter_newsanddiscount_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscount',
            name='date_published',
            field=models.DateField(),
        ),
    ]
