# Generated by Django 4.0.6 on 2022-08-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0016_alter_newsanddiscount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscount',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
