# Generated by Django 4.0.6 on 2022-08-21 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0017_alter_newsanddiscount_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsanddiscinbanner',
            old_name='url',
            new_name='trailer_url',
        ),
    ]
