# Generated by Django 4.0.6 on 2022-08-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0018_rename_url_newsanddiscinbanner_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsanddiscount',
            old_name='url',
            new_name='trailer_url',
        ),
    ]
