# Generated by Django 4.0.6 on 2022-08-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0020_alter_newsanddiscount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
