# Generated by Django 4.0.6 on 2022-08-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0022_backgroundphone_bannersinthetop_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Color', 'Color')], max_length=16, null=True)),
                ('color', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundPhone',
        ),
    ]
