# Generated by Django 4.0.6 on 2022-08-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0023_background_delete_backgroundphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='color',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='background',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='background',
            name='type',
            field=models.CharField(choices=[('Photo', 'Photo'), ('Color', 'Color')], default='Color', max_length=16),
        ),
    ]
