# Generated by Django 4.0.6 on 2022-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0024_alter_background_color_alter_background_main_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscinbanner',
            name='trailer_url',
            field=models.CharField(max_length=64),
        ),
    ]
