# Generated by Django 4.0.6 on 2022-08-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0025_alter_newsanddiscinbanner_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='phone_number2',
            field=models.IntegerField(null=True),
        ),
    ]
