# Generated by Django 4.0.6 on 2022-08-28 09:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0028_alter_mainpage_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
