# Generated by Django 4.0.6 on 2022-08-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0029_alter_mainpage_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='description',
            new_name='definition',
        ),
    ]
