# Generated by Django 4.0.6 on 2022-09-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0032_newsanddiscount_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='description_uk',
        ),
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='name_uk',
        ),
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='trailer_url_ru',
        ),
        migrations.RemoveField(
            model_name='newsanddiscount',
            name='trailer_url_uk',
        ),
    ]
