# Generated by Django 4.1.1 on 2022-09-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0034_newsanddiscount_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pages',
            name='name_uk',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
