# Generated by Django 4.0.6 on 2022-07-08 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=128)),
                ('keywords', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages_app.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to='')),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndDiscont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'News'), ('Discont', 'Discont')], max_length=16)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=256)),
                ('main_photo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='news_and_disc_in_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('News', 'News'), ('Discont', 'Discont')], max_length=16)),
                ('main_photo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('text', models.TextField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages_app.banners')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_text', models.TextField()),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.AddField(
            model_name='banners',
            name='top_in_main',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery'),
        ),
    ]
