# Generated by Django 4.0.6 on 2022-07-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='news_and_disc_in_banner',
            new_name='NewsAndDiscInBanner',
        ),
    ]
