# Generated by Django 4.0.6 on 2022-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0002_rename_news_and_disc_in_banner_newsanddiscinbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsanddiscont',
            name='date_published',
            field=models.DateField(),
        ),
    ]
