# Generated by Django 4.0.6 on 2022-07-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_app', '0003_alter_newsanddiscont_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
