# Generated by Django 4.0.6 on 2022-07-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to='')),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateField()),
                ('description', models.TextField()),
                ('scheme', models.JSONField()),
                ('main_photo', models.ImageField(upload_to='')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('main_photo', models.ImageField(upload_to='')),
                ('trailer_url', models.URLField()),
                ('type', models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('IMAX', 'IMAX')], max_length=16)),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.IntegerField()),
                ('day', models.DateField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.cinema')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Kontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
                ('coordinate', models.CharField(max_length=256)),
                ('photo_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages_app.gallery')),
            ],
        ),
    ]
