# Generated by Django 4.0.6 on 2022-08-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_remove_movie_type_movie_is_2d_movie_is_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='banner_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
