# Generated by Django 4.0.6 on 2022-08-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0007_alter_movie_trailer_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='descriptionn',
        ),
    ]
