# Generated by Django 4.0.6 on 2022-08-31 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0008_rename_description_movie_descriptionn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='descriptionn',
            new_name='description',
        ),
    ]
