# Generated by Django 4.0.6 on 2022-08-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0010_rename_description_movie_definition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='definition',
            new_name='description',
        ),
    ]
