# Generated by Django 4.0.6 on 2022-09-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0013_remove_session_end_date_remove_session_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
