# Generated by Django 4.0.6 on 2022-09-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0014_alter_session_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='day',
        ),
    ]
