# Generated by Django 4.0.6 on 2022-09-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0015_remove_session_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
    ]
