# Generated by Django 4.1.1 on 2022-09-14 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0017_alter_session_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cinema_app.hall'),
        ),
    ]
