# Generated by Django 4.1.1 on 2022-09-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0020_movie_description_ru_movie_description_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uk',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
