# Generated by Django 4.1.1 on 2022-09-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_admin', '0002_alter_template_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
